/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sai Tejaswini.M.V
 */
public class list extends javax.swing.JFrame {

    /**
     * Creates new form list
     */
    Student_authentication s=new Student_authentication();
    Teacher_authentication t=new Teacher_authentication();
    public list() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton27 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        buttonGroup20 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        p1 = new javax.swing.JRadioButton();
        a1 = new javax.swing.JRadioButton();
        p2 = new javax.swing.JRadioButton();
        a2 = new javax.swing.JRadioButton();
        p3 = new javax.swing.JRadioButton();
        a3 = new javax.swing.JRadioButton();
        p4 = new javax.swing.JRadioButton();
        a4 = new javax.swing.JRadioButton();
        p5 = new javax.swing.JRadioButton();
        a5 = new javax.swing.JRadioButton();
        p6 = new javax.swing.JRadioButton();
        a6 = new javax.swing.JRadioButton();
        p7 = new javax.swing.JRadioButton();
        a7 = new javax.swing.JRadioButton();
        p8 = new javax.swing.JRadioButton();
        a8 = new javax.swing.JRadioButton();
        p9 = new javax.swing.JRadioButton();
        a9 = new javax.swing.JRadioButton();
        p10 = new javax.swing.JRadioButton();
        a10 = new javax.swing.JRadioButton();
        p11 = new javax.swing.JRadioButton();
        a11 = new javax.swing.JRadioButton();
        p12 = new javax.swing.JRadioButton();
        a12 = new javax.swing.JRadioButton();
        p13 = new javax.swing.JRadioButton();
        a13 = new javax.swing.JRadioButton();
        p14 = new javax.swing.JRadioButton();
        a14 = new javax.swing.JRadioButton();
        p15 = new javax.swing.JRadioButton();
        a15 = new javax.swing.JRadioButton();
        p16 = new javax.swing.JRadioButton();
        a16 = new javax.swing.JRadioButton();
        p17 = new javax.swing.JRadioButton();
        a17 = new javax.swing.JRadioButton();
        p18 = new javax.swing.JRadioButton();
        a18 = new javax.swing.JRadioButton();
        p19 = new javax.swing.JRadioButton();
        a19 = new javax.swing.JRadioButton();
        p20 = new javax.swing.JRadioButton();
        a20 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        jRadioButton27.setText("jRadioButton27");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(p1);
        p1.setText("present");

        buttonGroup1.add(a1);
        a1.setText("absent");

        buttonGroup2.add(p2);
        p2.setText("present");

        buttonGroup2.add(a2);
        a2.setText("absent");
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });

        buttonGroup3.add(p3);
        p3.setText("present");

        buttonGroup3.add(a3);
        a3.setText("absent");

        buttonGroup4.add(p4);
        p4.setText("present");
        p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4ActionPerformed(evt);
            }
        });

        buttonGroup4.add(a4);
        a4.setText("absent");

        buttonGroup5.add(p5);
        p5.setText("present");

        buttonGroup5.add(a5);
        a5.setText("absent");

        buttonGroup6.add(p6);
        p6.setText("present");

        buttonGroup6.add(a6);
        a6.setText("absent");

        buttonGroup7.add(p7);
        p7.setText("present");

        buttonGroup7.add(a7);
        a7.setText("absent");

        buttonGroup8.add(p8);
        p8.setText("present");

        buttonGroup8.add(a8);
        a8.setText("absent");

        buttonGroup9.add(p9);
        p9.setText("present");
        p9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p9ActionPerformed(evt);
            }
        });

        buttonGroup9.add(a9);
        a9.setText("absent");

        buttonGroup10.add(p10);
        p10.setText("present");
        p10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p10ActionPerformed(evt);
            }
        });

        buttonGroup10.add(a10);
        a10.setText("absent");

        buttonGroup11.add(p11);
        p11.setText("present");

        buttonGroup11.add(a11);
        a11.setText("absent");

        buttonGroup12.add(p12);
        p12.setText("present");

        buttonGroup12.add(a12);
        a12.setText("absent");

        buttonGroup13.add(p13);
        p13.setText("present");

        buttonGroup13.add(a13);
        a13.setText("absent");

        buttonGroup14.add(p14);
        p14.setText("present");

        buttonGroup14.add(a14);
        a14.setText("absent");

        buttonGroup15.add(p15);
        p15.setText("present");

        buttonGroup15.add(a15);
        a15.setText("absent");

        buttonGroup16.add(p16);
        p16.setText("present");

        buttonGroup16.add(a16);
        a16.setText("absent");

        buttonGroup17.add(p17);
        p17.setText("present");

        buttonGroup17.add(a17);
        a17.setText("absent");

        buttonGroup18.add(p18);
        p18.setText("present");
        p18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p18ActionPerformed(evt);
            }
        });

        buttonGroup18.add(a18);
        a18.setText("absent");
        a18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a18ActionPerformed(evt);
            }
        });

        buttonGroup19.add(p19);
        p19.setText("present");

        buttonGroup19.add(a19);
        a19.setText("absent");

        buttonGroup20.add(p20);
        p20.setText("present");
        p20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p20ActionPerformed(evt);
            }
        });

        buttonGroup20.add(a20);
        a20.setText("absent");

        jLabel1.setText("1");

        jLabel2.setText("2");

        jLabel3.setText("3");

        jLabel4.setText("4");

        jLabel5.setText("5");

        jLabel6.setText("6");

        jLabel7.setText("7");

        jLabel8.setText("8");

        jLabel9.setText("9");

        jLabel10.setText("10");

        jLabel11.setText("  11");

        jLabel12.setText("  12");

        jLabel13.setText("13");

        jLabel14.setText("14");

        jLabel15.setText("15");

        jLabel16.setText("16");

        jLabel17.setText("17");

        jLabel18.setText("18");

        jLabel19.setText("19");

        jLabel20.setText("20");

        jLabel21.setText("USN");

        jButton1.setText("dd");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ds");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("scs");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("wt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("dml");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel22.setText("Update and then choose");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p19)
                        .addGap(12, 12, 12)
                        .addComponent(a19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(p6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(p5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(p4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(p7)
                                    .addComponent(p8)
                                    .addComponent(p9)
                                    .addComponent(p10)
                                    .addComponent(p11)
                                    .addComponent(p12)
                                    .addComponent(p13)
                                    .addComponent(p14)
                                    .addComponent(p15)
                                    .addComponent(p16)
                                    .addComponent(p20)
                                    .addComponent(p17)
                                    .addComponent(p18))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(a17)
                                            .addComponent(a16)
                                            .addComponent(a15)
                                            .addComponent(a14)
                                            .addComponent(a13)
                                            .addComponent(a12)
                                            .addComponent(a11)
                                            .addComponent(a10)
                                            .addComponent(a9)
                                            .addComponent(a8)
                                            .addComponent(a7)
                                            .addComponent(a4)
                                            .addComponent(a6)
                                            .addComponent(a5)
                                            .addComponent(a18)
                                            .addComponent(a3)
                                            .addComponent(a2)
                                            .addComponent(a1)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(a20))))
                            .addComponent(p2)
                            .addComponent(p3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel10))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(5, 5, 5)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(10, 10, 10)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel20))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(23, 23, 23)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel21)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel11)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p1)
                            .addComponent(a1)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p2)
                            .addComponent(a2)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3)
                    .addComponent(a3)
                    .addComponent(jLabel3)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a4)
                    .addComponent(p4)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a5)
                    .addComponent(p5)
                    .addComponent(jLabel5)
                    .addComponent(jButton3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p6)
                            .addComponent(a6)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p7)
                            .addComponent(a7)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p8)
                            .addComponent(a8)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p9)
                            .addComponent(a9)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p10)
                    .addComponent(a10)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p11)
                    .addComponent(a11)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p12)
                    .addComponent(a12)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p13)
                    .addComponent(a13)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p14)
                    .addComponent(a14)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p15)
                    .addComponent(a15)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p16)
                    .addComponent(a16)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p17)
                    .addComponent(a17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p18)
                    .addComponent(a18)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p19)
                    .addComponent(a19)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p20)
                    .addComponent(a20)
                    .addComponent(jLabel20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a18ActionPerformed

    private void p18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p18ActionPerformed

    private void p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p4ActionPerformed

    private void p9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p9ActionPerformed

    private void p10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p10ActionPerformed

    private void p20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p20ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(p1.isSelected())
        {
             s.edit(1, 4, "1");
        }
        if(p2.isSelected())
        {
             s.edit(2, 4, "1");
        }
         if(p3.isSelected())
        {
             s.edit(3, 4, "1");
        }
          if(p4.isSelected())
        {
             s.edit(4, 4, "1");
        }
         if(p5.isSelected())
        {
             s.edit(5, 4, "1");
        }
         if(p6.isSelected())
        {
             s.edit(6, 4, "1");
        }
          if(p7.isSelected())
        {
             s.edit(7, 4, "1");
        }
          if(p8.isSelected())
        {
             s.edit(8, 4, "1");
        }
          if(p9.isSelected())
        {
             s.edit(9, 4, "1");
        }
           if(p10.isSelected())
        {
             s.edit(10, 4, "1");
        }
          if(p11.isSelected())
        {
             s.edit(11, 4, "1");
        }
           if(p12.isSelected())
        {
             s.edit(12, 4, "1");
        }
            if(p13.isSelected())
        {
             s.edit(13, 4, "1");
        }
          if(p14.isSelected())
        {
             s.edit(14, 4, "1");
        }
           if(p15.isSelected())
        {
             s.edit(15, 4, "1");
        }
          if(p15.isSelected())
        {
             s.edit(15, 4, "1");
        }
          if(p16.isSelected())
        {
             s.edit(16, 4, "1");
        }
          if(p17.isSelected())
        {
             s.edit(18, 4, "1");
        }
          if(p18.isSelected())
        {
             s.edit(18, 4, "1");
        }
           if(p19.isSelected())
        {
             s.edit(19, 4, "1");
        }
         if(p20.isSelected())
        {
             s.edit(20, 4, "1");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(p1.isSelected())
        {
             s.edit(1, 5, "1");
        }
        if(p2.isSelected())
        {
             s.edit(2, 5, "1");
        }
         if(p3.isSelected())
        {
             s.edit(3, 5, "1");
        }
          if(p4.isSelected())
        {
             s.edit(4, 5, "1");
        }
         if(p5.isSelected())
        {
             s.edit(5, 5, "1");
        }
         if(p6.isSelected())
        {
             s.edit(6, 5, "1");
        }
          if(p7.isSelected())
        {
             s.edit(7, 5, "1");
        }
          if(p8.isSelected())
        {
             s.edit(8, 5, "1");
        }
          if(p9.isSelected())
        {
             s.edit(9, 5, "1");
        }
           if(p10.isSelected())
        {
             s.edit(10, 5, "1");
        }
          if(p11.isSelected())
        {
             s.edit(11, 5, "1");
        }
           if(p12.isSelected())
        {
             s.edit(12, 5, "1");
        }
            if(p13.isSelected())
        {
             s.edit(13, 5, "1");
        }
          if(p14.isSelected())
        {
             s.edit(14, 5, "1");
        }
           if(p15.isSelected())
        {
             s.edit(15, 5, "1");
        }
          if(p15.isSelected())
        {
             s.edit(15, 5, "1");
        }
          if(p16.isSelected())
        {
             s.edit(16, 5, "1");
        }
          if(p17.isSelected())
        {
             s.edit(18, 5, "1");
        }
          if(p18.isSelected())
        {
             s.edit(18, 5, "1");
        }
           if(p19.isSelected())
        {
             s.edit(19, 5, "1");
        }
         if(p20.isSelected())
        {
             s.edit(20, 5, "1");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(p1.isSelected())
        {
             s.edit(1, 6, "1");
        }
        if(p2.isSelected())
        {
             s.edit(2, 6, "1");
        }
         if(p3.isSelected())
        {
             s.edit(3, 6, "1");
        }
          if(p4.isSelected())
        {
             s.edit(4, 6, "1");
        }
         if(p5.isSelected())
        {
             s.edit(5, 6, "1");
        }
         if(p6.isSelected())
        {
             s.edit(6, 6, "1");
        }
          if(p7.isSelected())
        {
             s.edit(7, 6, "1");
        }
          if(p8.isSelected())
        {
             s.edit(8, 6, "1");
        }
          if(p9.isSelected())
        {
             s.edit(9, 6, "1");
        }
           if(p10.isSelected())
        {
             s.edit(10, 6, "1");
        }
          if(p11.isSelected())
        {
             s.edit(11, 6, "1");
        }
           if(p12.isSelected())
        {
             s.edit(12, 6, "1");
        }
            if(p13.isSelected())
        {
             s.edit(13, 6, "1");
        }
          if(p14.isSelected())
        {
             s.edit(14, 6, "1");
        }
           if(p15.isSelected())
        {
             s.edit(15, 6, "1");
        }
          if(p15.isSelected())
        {
             s.edit(15, 6, "1");
        }
          if(p16.isSelected())
        {
             s.edit(16, 6, "1");
        }
          if(p17.isSelected())
        {
             s.edit(18, 6, "1");
        }
          if(p18.isSelected())
        {
             s.edit(18, 6, "1");
        }
           if(p19.isSelected())
        {
             s.edit(19, 6, "1");
        }
         if(p20.isSelected())
        {
             s.edit(20, 6, "1");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(p1.isSelected())
        {
             s.edit(1, 7, "1");
        }
        if(p2.isSelected())
        {
             s.edit(2, 7, "1");
        }
         if(p3.isSelected())
        {
             s.edit(3, 7, "1");
        }
          if(p4.isSelected())
        {
             s.edit(4, 7, "1");
        }
         if(p5.isSelected())
        {
             s.edit(5, 7, "1");
        }
         if(p6.isSelected())
        {
             s.edit(6, 7, "1");
        }
          if(p7.isSelected())
        {
             s.edit(7, 7, "1");
        }
          if(p8.isSelected())
        {
             s.edit(8, 7, "1");
        }
          if(p9.isSelected())
        {
             s.edit(9, 7, "1");
        }
           if(p10.isSelected())
        {
             s.edit(10, 7, "1");
        }
          if(p11.isSelected())
        {
             s.edit(11, 7, "1");
        }
           if(p12.isSelected())
        {
             s.edit(12, 7, "1");
        }
            if(p13.isSelected())
        {
             s.edit(13, 7, "1");
        }
          if(p14.isSelected())
        {
             s.edit(14, 7, "1");
        }
           if(p15.isSelected())
        {
             s.edit(15, 7, "1");
        }
          if(p15.isSelected())
        {
             s.edit(15, 7, "1");
        }
          if(p16.isSelected())
        {
             s.edit(16, 7, "1");
        }
          if(p17.isSelected())
        {
             s.edit(18, 7, "1");
        }
          if(p18.isSelected())
        {
             s.edit(18, 7, "1");
        }
           if(p19.isSelected())
        {
             s.edit(19, 7, "1");
        }
         if(p20.isSelected())
        {
             s.edit(20, 7, "1");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(p1.isSelected())
        {
             s.edit(1, 8, "1");
        }
        if(p2.isSelected())
        {
             s.edit(2, 8, "1");
        }
         if(p3.isSelected())
        {
             s.edit(3, 8, "1");
        }
          if(p4.isSelected())
        {
             s.edit(4, 8, "1");
        }
         if(p5.isSelected())
        {
             s.edit(5, 8, "1");
        }
         if(p6.isSelected())
        {
             s.edit(6, 8, "1");
        }
          if(p7.isSelected())
        {
             s.edit(7, 8, "1");
        }
          if(p8.isSelected())
        {
             s.edit(8, 8, "1");
        }
          if(p9.isSelected())
        {
             s.edit(9, 8, "1");
        }
           if(p10.isSelected())
        {
             s.edit(10, 8, "1");
        }
          if(p11.isSelected())
        {
             s.edit(11, 8, "1");
        }
           if(p12.isSelected())
        {
             s.edit(12, 8, "1");
        }
            if(p13.isSelected())
        {
             s.edit(13, 8, "1");
        }
          if(p14.isSelected())
        {
             s.edit(14, 8, "1");
        }
           if(p15.isSelected())
        {
             s.edit(15, 8, "1");
        }
          if(p15.isSelected())
        {
             s.edit(15, 8, "1");
        }
          if(p16.isSelected())
        {
             s.edit(16, 8, "1");
        }
          if(p17.isSelected())
        {
             s.edit(18, 8, "1");
        }
          if(p18.isSelected())
        {
             s.edit(18, 8, "1");
        }
           if(p19.isSelected())
        {
             s.edit(19, 8, "1");
        }
         if(p20.isSelected())
        {
             s.edit(20, 8, "1");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new list().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a1;
    private javax.swing.JRadioButton a10;
    private javax.swing.JRadioButton a11;
    private javax.swing.JRadioButton a12;
    private javax.swing.JRadioButton a13;
    private javax.swing.JRadioButton a14;
    private javax.swing.JRadioButton a15;
    private javax.swing.JRadioButton a16;
    private javax.swing.JRadioButton a17;
    private javax.swing.JRadioButton a18;
    private javax.swing.JRadioButton a19;
    private javax.swing.JRadioButton a2;
    private javax.swing.JRadioButton a20;
    private javax.swing.JRadioButton a3;
    private javax.swing.JRadioButton a4;
    private javax.swing.JRadioButton a5;
    private javax.swing.JRadioButton a6;
    private javax.swing.JRadioButton a7;
    private javax.swing.JRadioButton a8;
    private javax.swing.JRadioButton a9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup20;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton p1;
    private javax.swing.JRadioButton p10;
    private javax.swing.JRadioButton p11;
    private javax.swing.JRadioButton p12;
    private javax.swing.JRadioButton p13;
    private javax.swing.JRadioButton p14;
    private javax.swing.JRadioButton p15;
    private javax.swing.JRadioButton p16;
    private javax.swing.JRadioButton p17;
    private javax.swing.JRadioButton p18;
    private javax.swing.JRadioButton p19;
    private javax.swing.JRadioButton p2;
    private javax.swing.JRadioButton p20;
    private javax.swing.JRadioButton p3;
    private javax.swing.JRadioButton p4;
    private javax.swing.JRadioButton p5;
    private javax.swing.JRadioButton p6;
    private javax.swing.JRadioButton p7;
    private javax.swing.JRadioButton p8;
    private javax.swing.JRadioButton p9;
    // End of variables declaration//GEN-END:variables
}
